apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: {{ .Release.Name }}-role-get-nodes
rules:
  - apiGroups: [""]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list"]
  - apiGroups: [ "" ]
    resources: [ "pods/binding" ]
    verbs: ["create", "update", "patch", "delete" ]
  - apiGroups: [ "k8s.codeflix.com" ]
    resources: [ "statefulsetschedulers" ]
    verbs: ["get", "list"]
