apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: statefulsetschedulers.k8s.codeflix.com
  labels:
    app.kubernetes.io/component: statefulset-scheduler
    app.kubernetes.io/name: statefulset-cluster-scheduler
    app.kubernetes.io/part-of: codeflix
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: k8s.codeflix.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schedulerName:
                  type: string
                  default: statefulset-scheduler
                podName:
                  type: string
                nodeNames:
                  type: array
                  items:
                    type: string
              required:
                - podName
                - nodeNames
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: statefulsetschedulers
    # singular name to be used as an alias on the CLI and for display
    singular: statefulsetscheduler
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: StatefulSetScheduler
    listKind: StatefulSetSchedulerList