apiVersion: k8s.codeflix.com/v1
kind: StatefulSetScheduler
metadata:
  name: nginx-statefulset-scheduler
  namespace: test
spec:
  schedulerName: statefulset-scheduler # optional
  podName: web # pod name of statefulset (e.g. if web-01 will be created, web is the correct name)
  nodeNames:
    - node-01 # web-0 will be scheduled here, mapping by index
    - node-02 # web-1 and so on